.PHONY: clean

run:
	dotnet run -c Release --project CodeBetter.Ingestor.csproj /Users/alessandrosantini/Development/psp/bo-api-transactions/TransactionModuleAPI.sln

build:
	dotnet build -c Release

# This Makefile is used to build the CodeBetter.Ingestor project.
clean:
	rm -rf bin obj